services:
  frontend-dev:
    profiles:
      - development
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    env_file:
      - .env

  frontend-prod:
    profiles:
      - production
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env